# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
baseurl:          /
url:              http://localhost:9001
encoding:         UTF-8

# Custom vars
current_version:  0.0.1
repo:             https://github.com/michaelbowlin/invent-framework

download:
  source:         https://github.com/michaelbowlin/invent-framework/archive/master.zip
  dist:           https://github.com/michaelbowlin/invent-framework/releases/download/v0.1.1/invent-framework-0.0.1-dist.zip
